# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-22 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20160319_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='condition',
            field=models.CharField(choices=[('New', 'New'), ('Slightly Used', 'Slightly Used'), ('Used', 'Used'), ('Very Used', 'Very Used'), ('Bad', 'Bad')], max_length=32),
        ),
    ]
