# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-05 23:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, max_length=500)),
                ('ratings', models.CharField(choices=[('0', '0'), ('0.5', '0.5'), ('1.0', '1.0'), ('1.5', '1.5'), ('2.0', '2.0'), ('2.5', '2.5'), ('3.0', '3.0'), ('3.5', '3.5'), ('4.0', '4.0'), ('4.5', '4.5'), ('5.0', '5.0')], max_length=3)),
                ('date', models.DateTimeField(verbose_name='date posted')),
                ('reviewed', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='reviewed', to='profiles.Profile')),
                ('reviewer', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to='profiles.Profile')),
            ],
        ),
    ]
