# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-05 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phoneNumber',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='postalCode',
            field=models.CharField(max_length=7),
        ),
    ]
