# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-05 23:56
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameName', models.CharField(max_length=128)),
                ('console', models.CharField(max_length=128)),
                ('description', models.TextField(max_length=2048)),
                ('date', models.DateTimeField(verbose_name='date posted')),
                ('condition', models.CharField(choices=[('New', 'New'), ('Slightly Used', 'Slightly Used'), ('Used', 'Used'), ('Very Used', 'Very Used'), ('Bad', 'Bad')], max_length=32)),
                ('image', models.ImageField(blank=True, upload_to='media/post_images')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
            ],
        ),
    ]
