# Generated by Django 2.0.7 on 2018-10-13 19:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='group',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
