# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-18 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameName', models.CharField(max_length=128)),
                ('console', models.CharField(blank=True, max_length=128)),
                ('description', models.TextField(max_length=2048)),
                ('date', models.DateTimeField(verbose_name='date posted')),
                ('condition', models.CharField(choices=[('1', 'New'), ('2', 'Slightly Used'), ('3', 'Used'), ('4', 'Very Used'), ('5', 'Bad')], max_length=32)),
                ('price', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
            ],
        ),
    ]
