# Generated by Django 2.0.7 on 2018-10-08 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dateUpdated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date updated'),
        ),
    ]
